# Generated by Django 3.0.8 on 2020-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fips', models.IntegerField()),
                ('country_region', models.CharField(max_length=50)),
                ('province_state', models.CharField(max_length=50)),
            ],
        ),
    ]
