# Generated by Django 3.0.8 on 2020-07-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddata',
            name='active_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
